### PR TITLE
Add smoke tests

### PR DESCRIPTION
**Pull request by ErikSchierboom**
- Ignore more files from Docker context
- Ignore generated mapping.json and representation.txt files
- Add workflow to run smoke tests
- Add script to run representer and run tests
- Update expected files

### CODE REVIEW

**Comment by verdammelt** [comment]
It looks like this change is duplicating existing tests (but is adding the jobs to run the tests..)

Or am I reading this incorrectly?

**Comment by ErikSchierboom** [comment]
> Or am I reading this incorrectly?

You are. I'm just changing the names of the files. And then running them as smoke tests.

**Comment by verdammelt** [comment]
I see duplicated files (_i.e._ there is now `expected-mapping.json` as well as `mapping.json`). 

The existing tests are expecting `mapping.json` but could be changed to look at `expected-mapping.json`

*OR*

I could remove those end-to-end tests which are now duplicated by these smoke tests.

**Review by verdammelt — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Now I see it! I'll update when I have time. Sorry about that!

**Comment by ErikSchierboom** [comment]
> I will approve this PR and create an issue about removing the now duplicated end-to-end tests. 

Thanks!

**Pull request merged**
